import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: 'Catchall Layout',
    template: '%s | Catchall Layout',
  },
  description: 'Generated by Next.js',
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'lightblue',
            padding: '10px',
          }}
        >
          <p>Header for catchall layout</p>
        </header>
        {children}
        
        <footer
          style={{
            
            backgroundColor: 'lightblue',
            padding: '10px',
          }}>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  );
}
